### ISSUE TITLE
Cant use the namespace

### ISSUE THREAD

**Issue by mace015** [psecio/csrf#1]
Hi, I'm trying to use your package for CSRF tokens, but I cant use the namespace `\Psecio\Csrf\Manager` because your composer.json is not correct.

Right now its:

``` json
"autoload": {
        "psr-0": {
            "Psecio": "src/"
        }
    }
```

But it should be:

``` json
"autoload": {
        "psr-4": {
            "Psecio\\": "Psecio/"
        }
    }
```

Could you please fix this?

**Comment by sandrokeil** [comment]
@enygma I have the same problem.

**Comment by silas229** [comment]
Since it doesn't look like it will ever be fixed, here is a workaround for your own `composer.json` that doesn't require changing the source files:
```php
"autoload": {
    "psr-4": {
      "Psecio\\": "vendor/psecio/csrf/Psecio/"
    }
  }
```
